name=Remocon
version=3.0.0
author=Taeo Lee <sixgen@gmail.com>
maintainer=Taeo Lee <sixgen@gmail.com>
sentence=IOSignal Arduino examples for remocon.kr and test.iosignal.net.
paragraph=Control DIY Arduino IoT remote control system with the web app.
category=Communication
url=https://github.com/remocons/remocon-arduino
architectures=*
depends=IOSignal,Crypto,Boho,Bounce2,U8g2,IRremote,WiFiManager,FastLED,Ethernet
